vich_uploader:
    db_driver: orm
    mappings:
        makes:
            uri_prefix: /images/makes
            upload_destination: '%kernel.project_dir%/public/images/makes'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        common_models:
            uri_prefix: /images/models
            upload_destination: '%kernel.project_dir%/public/images/models'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        car_details:
            uri_prefix: /images/car_details
            upload_destination: '%kernel.project_dir%/public/images/car_details'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


