version: "3.6"

networks:
  backend:

services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - backend

  php:
    build:
      context: ./php/
      dockerfile: Dockerfile
    ports:
      - "8001:81"
    volumes:
      - ./app:/var/www/project
    networks:
      - backend

  mysql:
    image: mysql:8.0
    ports:
      - "4036:3306"
    volumes:
      - yourcar-mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf  # Mount custom configuration
    restart: always
    environment:
      - MYSQL_DATABASE=yourcar
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      - backend

  node:
    image: node:latest
    volumes:
      - ./app:/var/www/project
    working_dir: /var/www/project
    networks:
      - backend

volumes:
  yourcar-mysql: