<?php

namespace ContainerUOXE2hd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTireRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\TireRepository' shared autowired service.
     *
     * @return \App\Repository\TireRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/TireRepository.php';

        return $container->privates['App\\Repository\\TireRepository'] = new \App\Repository\TireRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
