<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CarDetails extends \App\Entity\CarDetails implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'speed', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'weight', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'fuelConsumption', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'drive', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'power', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'torque', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'eco', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'fuelConsumptionMixed', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'fuelConsumptionExtra', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'subModel', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'yearStart', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'yearFinish', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'engine', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'transmission', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'favourites', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'scales', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'ratings', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'tuning', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'age', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'purpose', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'size', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'engineLife'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'speed', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'weight', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'fuelConsumption', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'drive', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'power', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'torque', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'eco', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'fuelConsumptionMixed', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'fuelConsumptionExtra', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'subModel', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'yearStart', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'yearFinish', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'engine', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'transmission', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'favourites', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'scales', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'ratings', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'tuning', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'age', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'purpose', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'size', '' . "\0" . 'App\\Entity\\CarDetails' . "\0" . 'engineLife'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CarDetails $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSpeed(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpeed', []);

        return parent::getSpeed();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpeed(int $speed): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpeed', [$speed]);

        return parent::setSpeed($speed);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeight(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeight', []);

        return parent::getWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeight(float $weight): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeight', [$weight]);

        return parent::setWeight($weight);
    }

    /**
     * {@inheritDoc}
     */
    public function getFuelConsumption(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuelConsumption', []);

        return parent::getFuelConsumption();
    }

    /**
     * {@inheritDoc}
     */
    public function setFuelConsumption(float $fuelConsumption): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuelConsumption', [$fuelConsumption]);

        return parent::setFuelConsumption($fuelConsumption);
    }

    /**
     * {@inheritDoc}
     */
    public function getDrive(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDrive', []);

        return parent::getDrive();
    }

    /**
     * {@inheritDoc}
     */
    public function setDrive(string $drive): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDrive', [$drive]);

        return parent::setDrive($drive);
    }

    /**
     * {@inheritDoc}
     */
    public function getPower(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPower', []);

        return parent::getPower();
    }

    /**
     * {@inheritDoc}
     */
    public function setPower(float $power): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPower', [$power]);

        return parent::setPower($power);
    }

    /**
     * {@inheritDoc}
     */
    public function getEco(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEco', []);

        return parent::getEco();
    }

    /**
     * {@inheritDoc}
     */
    public function setEco(string $eco): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEco', [$eco]);

        return parent::setEco($eco);
    }

    /**
     * {@inheritDoc}
     */
    public function getFuelConsumptionMixed(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuelConsumptionMixed', []);

        return parent::getFuelConsumptionMixed();
    }

    /**
     * {@inheritDoc}
     */
    public function setFuelConsumptionMixed(float $fuelConsumptionMixed): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuelConsumptionMixed', [$fuelConsumptionMixed]);

        return parent::setFuelConsumptionMixed($fuelConsumptionMixed);
    }

    /**
     * {@inheritDoc}
     */
    public function getFuelConsumptionExtra(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuelConsumptionExtra', []);

        return parent::getFuelConsumptionExtra();
    }

    /**
     * {@inheritDoc}
     */
    public function setFuelConsumptionExtra(float $fuelConsumptionExtra): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuelConsumptionExtra', [$fuelConsumptionExtra]);

        return parent::setFuelConsumptionExtra($fuelConsumptionExtra);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubModel(): ?\App\Entity\SubModel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubModel', []);

        return parent::getSubModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubModel(?\App\Entity\SubModel $subModel): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubModel', [$subModel]);

        return parent::setSubModel($subModel);
    }

    /**
     * {@inheritDoc}
     */
    public function getYearStart(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYearStart', []);

        return parent::getYearStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setYearStart(int $yearStart): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYearStart', [$yearStart]);

        return parent::setYearStart($yearStart);
    }

    /**
     * {@inheritDoc}
     */
    public function getYearFinish(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYearFinish', []);

        return parent::getYearFinish();
    }

    /**
     * {@inheritDoc}
     */
    public function setYearFinish(?int $yearFinish): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYearFinish', [$yearFinish]);

        return parent::setYearFinish($yearFinish);
    }

    /**
     * {@inheritDoc}
     */
    public function getEngine(): ?\App\Entity\Engine
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEngine', []);

        return parent::getEngine();
    }

    /**
     * {@inheritDoc}
     */
    public function setEngine(?\App\Entity\Engine $engine): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEngine', [$engine]);

        return parent::setEngine($engine);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransmission(): ?\App\Entity\Transmission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransmission', []);

        return parent::getTransmission();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransmission(?\App\Entity\Transmission $transmission): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransmission', [$transmission]);

        return parent::setTransmission($transmission);
    }

    /**
     * {@inheritDoc}
     */
    public function getTorque(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTorque', []);

        return parent::getTorque();
    }

    /**
     * {@inheritDoc}
     */
    public function setTorque(int $torque): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTorque', [$torque]);

        return parent::setTorque($torque);
    }

    /**
     * {@inheritDoc}
     */
    public function getFavourites(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFavourites', []);

        return parent::getFavourites();
    }

    /**
     * {@inheritDoc}
     */
    public function addFavourite(\App\Entity\Favourite $favourite): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFavourite', [$favourite]);

        return parent::addFavourite($favourite);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFavourite(\App\Entity\Favourite $favourite): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFavourite', [$favourite]);

        return parent::removeFavourite($favourite);
    }

    /**
     * {@inheritDoc}
     */
    public function isFavouredByUser(\App\Entity\User $user): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFavouredByUser', [$user]);

        return parent::isFavouredByUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function isScaledByUser(\App\Entity\User $user): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isScaledByUser', [$user]);

        return parent::isScaledByUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getScales(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScales', []);

        return parent::getScales();
    }

    /**
     * {@inheritDoc}
     */
    public function addScale(\App\Entity\Scale $scale): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addScale', [$scale]);

        return parent::addScale($scale);
    }

    /**
     * {@inheritDoc}
     */
    public function removeScale(\App\Entity\Scale $scale): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeScale', [$scale]);

        return parent::removeScale($scale);
    }

    /**
     * {@inheritDoc}
     */
    public function getRatings(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRatings', []);

        return parent::getRatings();
    }

    /**
     * {@inheritDoc}
     */
    public function addRating(\App\Entity\Rating $rating): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRating', [$rating]);

        return parent::addRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRating(\App\Entity\Rating $rating): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRating', [$rating]);

        return parent::removeRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function getTuning(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTuning', []);

        return parent::getTuning();
    }

    /**
     * {@inheritDoc}
     */
    public function setTuning(?string $tuning): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTuning', [$tuning]);

        return parent::setTuning($tuning);
    }

    /**
     * {@inheritDoc}
     */
    public function getAge(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', []);

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setAge(int $age): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAge', [$age]);

        return parent::setAge($age);
    }

    /**
     * {@inheritDoc}
     */
    public function getPurpose(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurpose', []);

        return parent::getPurpose();
    }

    /**
     * {@inheritDoc}
     */
    public function setPurpose(string $purpose): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPurpose', [$purpose]);

        return parent::setPurpose($purpose);
    }

    /**
     * {@inheritDoc}
     */
    public function getSize(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSize', []);

        return parent::getSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setSize(?string $size): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSize', [$size]);

        return parent::setSize($size);
    }

    /**
     * {@inheritDoc}
     */
    public function getEngineLife(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEngineLife', []);

        return parent::getEngineLife();
    }

    /**
     * {@inheritDoc}
     */
    public function setEngineLife(string $engineLife): \App\Entity\CarDetails
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEngineLife', [$engineLife]);

        return parent::setEngineLife($engineLife);
    }

}
