<?php

namespace ContainerKgEXQbW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilterRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\FilterRepository' shared autowired service.
     *
     * @return \App\Repository\FilterRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/FilterRepository.php';

        return $container->privates['App\\Repository\\FilterRepository'] = new \App\Repository\FilterRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
