<?php

namespace ContainerKgEXQbW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTireCrudControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\TireCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\TireCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/CrudControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractCrudController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/TireCrudController.php';

        $container->services['App\\Controller\\Admin\\TireCrudController'] = $instance = new \App\Controller\Admin\TireCrudController();

        $instance->setContainer(($container->privates['.service_locator.AJZghCA'] ?? $container->load('get_ServiceLocator_AJZghCAService'))->withContext('App\\Controller\\Admin\\TireCrudController', $container));

        return $instance;
    }
}
