#!/bin/bash
# make this file executable using:
# chmod +x ./app/pre-commit
# run command from YourCar-docker folder
# link this file to .git/hooks/pre-commit using:
# ln -s -f ../../app/pre-commit .git/hooks/pre-commit

# Clear Rector cache
docker compose -f compose.yml exec -T php rm -rf /tmp/rector_cached_files

# Run Rector
docker compose -f compose.yml exec -T php vendor/bin/rector process | tee .fixed
fgrep ') src/' .fixed | awk '{print $2}' | xargs -r git add
rm .fixed
#
## Run ECS (EasyCodingStandard)
docker compose -f compose.yml exec -T php vendor/bin/ecs check --fix | tee .fixed
fgrep ') src/' .fixed | awk '{print $2}' | xargs -r git add
rm .fixed
#
## Run PHP-CS-Fixer
docker compose -f compose.yml exec -T php vendor/bin/twig-cs-fixer --fix
#
#git add .
#
## Add all modified files to the current commit
#
## Run phpstan analyse
docker compose -f compose.yml exec -T php vendor/bin/phpstan -v