<?php

namespace ContainerYPZpCQr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CI4Fnd2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CI4Fnd2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CI4Fnd2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'modelRepo' => ['privates', 'App\\Repository\\ModelRepository', 'getModelRepositoryService', true],
        ], [
            'modelRepo' => 'App\\Repository\\ModelRepository',
        ]);
    }
}
