<?php

namespace ContainerYPZpCQr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFaultRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\FaultRepository' shared autowired service.
     *
     * @return \App\Repository\FaultRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/FaultRepository.php';

        return $container->privates['App\\Repository\\FaultRepository'] = new \App\Repository\FaultRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
