<?php

namespace ContainerYPZpCQr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRimRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\RimRepository' shared autowired service.
     *
     * @return \App\Repository\RimRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/RimRepository.php';

        return $container->privates['App\\Repository\\RimRepository'] = new \App\Repository\RimRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
