<?php

namespace ContainerPhJfMJo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I8253bsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I8253bs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I8253bs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'car' => ['privates', '.errored..service_locator.I8253bs.App\\Entity\\CarDetails', NULL, 'Cannot autowire service ".service_locator.I8253bs": it references class "App\\Entity\\CarDetails" but no such service exists.'],
            'scaleRepository' => ['privates', 'App\\Repository\\ScaleRepository', 'getScaleRepositoryService', true],
        ], [
            'car' => 'App\\Entity\\CarDetails',
            'scaleRepository' => 'App\\Repository\\ScaleRepository',
        ]);
    }
}
