<?php

namespace ContainerPhJfMJo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YDBsVhvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YDBsVhv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YDBsVhv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'finder' => ['privates', 'fos_elastica.manager.orm', 'getFosElastica_Manager_OrmService', true],
        ], [
            'finder' => '?',
        ]);
    }
}
