<?php

namespace ContainerPhJfMJo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarDetails2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.I8253bs.App\Entity\CarDetails' shared service.
     *
     * @return \App\Entity\CarDetails
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.I8253bs": it references class "App\\Entity\\CarDetails" but no such service exists.');
    }
}
