<?php

namespace ContainerPhJfMJo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MainController' shared autowired service.
     *
     * @return \App\Controller\MainController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/MainController.php';

        $container->services['App\\Controller\\MainController'] = $instance = new \App\Controller\MainController(($container->services['App\\Controller\\RatingController'] ?? $container->load('getRatingControllerService')));

        $instance->setContainer(($container->privates['.service_locator.B8xSpvP'] ?? $container->load('get_ServiceLocator_B8xSpvPService'))->withContext('App\\Controller\\MainController', $container));

        return $instance;
    }
}
