<?php

namespace ContainerPhJfMJo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScaleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ScaleController' shared autowired service.
     *
     * @return \App\Controller\ScaleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ScaleController.php';

        $container->services['App\\Controller\\ScaleController'] = $instance = new \App\Controller\ScaleController();

        $instance->setContainer(($container->privates['.service_locator.B8xSpvP'] ?? $container->load('get_ServiceLocator_B8xSpvPService'))->withContext('App\\Controller\\ScaleController', $container));

        return $instance;
    }
}
