<?php

namespace ContainerJCeNvEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HLa0FTTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HLa0FTT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HLa0FTT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'finderCarDetails' => ['privates', 'fos_elastica.finder.cardetails', 'getFosElastica_Finder_CardetailsService', true],
            'scaleRepository' => ['privates', 'App\\Repository\\ScaleRepository', 'getScaleRepositoryService', true],
        ], [
            'finderCarDetails' => '?',
            'scaleRepository' => 'App\\Repository\\ScaleRepository',
        ]);
    }
}
