<?php

namespace ContainerJCeNvEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WQu24rLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WQu24rL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WQu24rL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carDetailsRepository' => ['privates', 'App\\Repository\\CarDetailsRepository', 'getCarDetailsRepositoryService', true],
            'subModelRepository' => ['privates', 'App\\Repository\\SubModelRepository', 'getSubModelRepositoryService', true],
        ], [
            'carDetailsRepository' => 'App\\Repository\\CarDetailsRepository',
            'subModelRepository' => 'App\\Repository\\SubModelRepository',
        ]);
    }
}
