<?php

namespace ContainerJCeNvEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LuKKtH5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.luKKtH5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.luKKtH5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carDetailsRepository' => ['privates', 'App\\Repository\\CarDetailsRepository', 'getCarDetailsRepositoryService', true],
            'engineRepository' => ['privates', 'App\\Repository\\EngineRepository', 'getEngineRepositoryService', true],
            'ratingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
        ], [
            'carDetailsRepository' => 'App\\Repository\\CarDetailsRepository',
            'engineRepository' => 'App\\Repository\\EngineRepository',
            'ratingRepository' => 'App\\Repository\\RatingRepository',
        ]);
    }
}
