<?php

namespace ContainerJCeNvEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_Manager_OrmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_elastica.manager.orm' shared service.
     *
     * @return \FOS\ElasticaBundle\Doctrine\RepositoryManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Manager/RepositoryManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/RepositoryManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Manager/RepositoryManager.php';

        $a = new \FOS\ElasticaBundle\Manager\RepositoryManager();
        $a->addIndex('cardetails', ($container->privates['fos_elastica.finder.cardetails'] ?? $container->load('getFosElastica_Finder_CardetailsService')));

        $container->privates['fos_elastica.manager.orm'] = $instance = new \FOS\ElasticaBundle\Doctrine\RepositoryManager(($container->services['doctrine'] ?? $container->getDoctrineService()), $a);

        $instance->addEntity('App\\Entity\\CarDetails', 'cardetails');

        return $instance;
    }
}
