<?php

namespace ContainerJCeNvEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_PagerProvider_CardetailsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_elastica.pager_provider.cardetails' shared service.
     *
     * @return \FOS\ElasticaBundle\Doctrine\ORMPagerProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Provider/PagerProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/ORMPagerProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/RegisterListenersService.php';

        return $container->privates['fos_elastica.pager_provider.cardetails'] = new \FOS\ElasticaBundle\Doctrine\ORMPagerProvider(($container->services['doctrine'] ?? $container->getDoctrineService()), new \FOS\ElasticaBundle\Doctrine\RegisterListenersService(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService())), 'App\\Entity\\CarDetails', ['batch_size' => 100, 'clear_object_manager' => true, 'debug_logging' => true, 'query_builder_method' => 'createQueryBuilder']);
    }
}
