<?php

namespace ContainerEBGBUTN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QmtTLZnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qmtTLZn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qmtTLZn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'finderModel' => ['privates', 'fos_elastica.finder.model', 'getFosElastica_Finder_ModelService', true],
        ], [
            'finderModel' => '?',
        ]);
    }
}
