<?php

namespace ContainerEBGBUTN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFaultFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FaultFormType' shared autowired service.
     *
     * @return \App\Form\FaultFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FaultFormType.php';

        return $container->privates['App\\Form\\FaultFormType'] = new \App\Form\FaultFormType(($container->services['translator'] ?? $container->getTranslatorService()));
    }
}
