<?php

namespace ContainerEBGBUTN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_Command_PopulateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_elastica.command.populate' shared service.
     *
     * @return \FOS\ElasticaBundle\Command\PopulateCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Command/PopulateCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Provider/PagerProviderRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Persister/PagerPersisterRegistry.php';

        $container->privates['fos_elastica.command.populate'] = $instance = new \FOS\ElasticaBundle\Command\PopulateCommand(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->privates['fos_elastica.index_manager'] ?? $container->load('getFosElastica_IndexManagerService')), new \FOS\ElasticaBundle\Provider\PagerProviderRegistry(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cardetails' => ['privates', 'fos_elastica.pager_provider.cardetails', 'getFosElastica_PagerProvider_CardetailsService', true],
            'cars' => ['privates', 'fos_elastica.pager_provider.cars', 'getFosElastica_PagerProvider_CarsService', true],
            'model' => ['privates', 'fos_elastica.pager_provider.model', 'getFosElastica_PagerProvider_ModelService', true],
        ], [
            'cardetails' => 'FOS\\ElasticaBundle\\Doctrine\\ORMPagerProvider',
            'cars' => 'FOS\\ElasticaBundle\\Doctrine\\ORMPagerProvider',
            'model' => 'FOS\\ElasticaBundle\\Doctrine\\ORMPagerProvider',
        ])), new \FOS\ElasticaBundle\Persister\PagerPersisterRegistry(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'in_place' => ['privates', 'fos_elastica.in_place_pager_persister', 'getFosElastica_InPlacePagerPersisterService', true],
        ], [
            'in_place' => 'FOS\\ElasticaBundle\\Persister\\InPlacePagerPersister',
        ])), ($container->privates['fos_elastica.resetter'] ?? $container->load('getFosElastica_ResetterService')));

        $instance->setName('fos:elastica:populate');

        return $instance;
    }
}
