<?php

namespace ContainerEBGBUTN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModelRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ModelRepository' shared autowired service.
     *
     * @return \App\Repository\ModelRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/ModelRepository.php';

        return $container->privates['App\\Repository\\ModelRepository'] = new \App\Repository\ModelRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
