<?php

namespace ContainerEBGBUTN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserLocateSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Subscribers\UserLocateSubscriber' shared autowired service.
     *
     * @return \App\Subscribers\UserLocateSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Subscribers/UserLocateSubscriber.php';

        return $container->privates['App\\Subscribers\\UserLocateSubscriber'] = new \App\Subscribers\UserLocateSubscriber(($container->services['session'] ?? $container->getSessionService()));
    }
}
