<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYPZpCQr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYPZpCQr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYPZpCQr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYPZpCQr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYPZpCQr\App_KernelDevDebugContainer([
    'container.build_hash' => 'YPZpCQr',
    'container.build_id' => '28a9e0a5',
    'container.build_time' => 1639512271,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYPZpCQr');
