<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKgEXQbW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKgEXQbW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKgEXQbW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKgEXQbW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKgEXQbW\App_KernelDevDebugContainer([
    'container.build_hash' => 'KgEXQbW',
    'container.build_id' => '3b7ed04e',
    'container.build_time' => 1637961364,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKgEXQbW');
